### ISSUE TITLE
%player% problem

### ISSUE THREAD

**Issue by efekurbann** [sneklingame/Rewards-GUI#2]
Hello, i have a question. How can i use player's name in config file? I tried %player%, <player> but not working for me.

**Comment by sneklingame** [comment]
Hey! I'm afraid that's not possible at the moment, but I'll start working on it and release it with some other features in the next version. (This may take a day or two). 

You can watch my progress and things I'll add in the next versions in the [To-Do list](https://github.com/sneklingame/Rewards-GUI/projects/1).

**Comment by efekurbann** [comment]
> Hey! I'm afraid that's not possible at the moment, but I'll start working on it and release it with some other features in the next version. (This may take a day or two).
> 
> You can watch my progress and things I'll add in the next versions in the [To-Do list](https://github.com/sneklingame/Rewards-GUI/projects/1).

k, thanks.

**Comment by sneklingame** [comment]
Added the %player% placeholder in update [1.2.2](https://www.spigotmc.org/resources/rewards-gui-mysql-vault.78262/update?update=334314).
