### ISSUE TITLE
Vault Support issue

### ISSUE THREAD

**Issue by ArcadeFighter** [sneklingame/Rewards-GUI#3]
Hello, i want use Rewards-GUI on lobby, and there is only Vault plugin, but your plugin can't be loaded because there is no economy plugin, is there any way to run without economy plugin?

Thank you.

**Comment by sneklingame** [comment]
Hi! The Vault dependency is from when the 'commands' feature hadn't yet been added, so it didn't make sense to run the plugin without Vault and an economy plugin. I've managed to completely forget about it, so thanks for letting me know! I'll remove it in the next update.

**Comment by sneklingame** [comment]
Fixed in [1.2.3](https://www.spigotmc.org/resources/rewards-gui-mysql-vault.78262/update?update=335832)!
