### ISSUE TITLE
%player%  does not work on the console

### ISSUE THREAD

**Issue by iJosePlay** [sneklingame/Rewards-GUI#4]
![Screenshot_2](https://user-images.githubusercontent.com/49538996/82099483-1996d980-96cd-11ea-9aa1-f4092bcbd5db.png)
![Screenshot_1](https://user-images.githubusercontent.com/49538996/82099493-1dc2f700-96cd-11ea-8a3b-f7e39c746ac7.png)

**Comment by sneklingame** [comment]
Hey! Thanks for letting me know. I just added it in [1.2.3](https://www.spigotmc.org/resources/rewards-gui-mysql-vault.78262/update?update=335832).
