### ISSUE TITLE
Console support or custom command

### ISSUE THREAD

**Issue by ArcadeFighter** [sneklingame/Rewards-GUI#5]
Hello, i have issue with command /rewards.
I using a PlatinumHubCore and there is command /rewards.
So, i can't use your menu, and i tried /reward and /rw for players, but no success...
Can you add some custom command or console support?
Thank you for help.

**Comment by sneklingame** [comment]
Hey! I could add configurable aliases, but it feels kind of redundant as Spigot has this feature implemented out-of-the-box. You should be able to create an alias in your `commands.yml `file. I'd use something like this:

`your-custom-command:`
`- "rewards:rw"`

You can read more about Spigot's aliases [here](https://bukkit.gamepedia.com/Commands.yml). You could also disable the PlatinumHubCore's reward command.

If players on your server don't directly use the command, you can always use `plugin:command`, ie. `rewards:rw`

This should solve your issue. If you have any more questions or/and need any further help, just let me know.

Also, what do you mean by this?
> Can you add some custom command or console support?

Thanks.

**Comment by ArcadeFighter** [comment]
> Can you add some custom command or console support?
I mean this, i have a npc, i can make an console command, because alternative ways of /rewards don't work, so this is reason to add it.
Thank you.

**Comment by sneklingame** [comment]
If you want an NPC to open the menu, use `/rewards:rw`. Still don't know what you mean by "console command", sorry.

**Comment by ArcadeFighter** [comment]
Like open Rewards gui with console command

**Comment by sneklingame** [comment]
> Like open Rewards gui with console command

Oh, I see. I actually thought I had already done that, so that's why I didn't get it. I'll definitely add it in the next version.

**Comment by sneklingame** [comment]
Added the console command in [1.2.4](https://www.spigotmc.org/resources/rewards-gui-mysql-vault.78262/update?update=336198).
