### ISSUE TITLE
MySQL error

### ISSUE THREAD

**Issue by TerrorGamesOff** [sneklingame/Rewards-GUI#7]
### Bug report

**Describe the bug**  
MySQL error. When i click on VIP+ reward a MySql error appears. I tried to copy/paste other reward configuration but is the same problem just with VIP+ Reward button.

**How to Reproduce**  
1. Use my configuration
2. Select VIP+ reward
3. See error

**Screenshots**  
https://pastebin.com/GQ3YM6x0

**Server details:**  
 - Server software: PaperSpigot
 - Version: 1.8.8

**Your config**  
https://pastebin.com/Uj0Cx1NG

**Console log**  
https://pastebin.com/GQ3YM6x0

**Does the issue occur with the default config?**  
Try running the plugin with the default generated config.yml. Does the bug still occur?
 - Yes

**Additional context**

**Comment by TerrorGamesOff** [comment]
I find the problem. The problem is "+" from "VIP+"

**Comment by sneklingame** [comment]
Hi, yeah, I thought the plus sign might be a problem, but you didn't even give me time to test it :) So, I guess the issue can be closed?

**Comment by TerrorGamesOff** [comment]
Yes you can close the issue. Sorry.
